import innovativeHtml from './templates/innovative.html?raw';
import quantumLeapHtml from './templates/quantumleap.html?raw';
import doctorPortfolio3dHtml from './templates/DoctorPortfolio3D.html?raw';
import constructionSimpleHtml from './templates/ConstructionSimple.html?raw';
import constructionHtml from './templates/Construction.html?raw';
import synergyBIHtml from './templates/SynergyBI.html?raw';

import innovativeImg from './images/innovative.png';
import quantumLeapImg from './images/quantumleap.png';
import doctorPortfolio3dImg from './images/DoctorPortfolio3D.png';
import constructionSimpleImg from './images/ConstructionSimple.png';
import constructionImg from './images/Construction.png';
import synergyBIImg from './images/SynergyBI.png';

export const MOCK_WEBSITES = [
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
  {
    id: "corp-landing-v3",
    title: "Innovate Inc. Landing Page",
    category: "Business",
    price: 5000,
    originalPrice: 6500,
    tags: [
      "Landing Page",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "CTA",
      "FAQ",
      "Testimonials",
      "Tailwind CSS",
    ],
    code: innovativeHtml,
    imagePath: innovativeImg, 
  },
  {
    id: "quantum-landing-v1",
    title: "Quantum Leap Digital Business ",
    category: "Technology",
    price: 8000,
    originalPrice: 8000,
    tags: [
      "Landing Page",
      "Futuristic",
      "Dark Mode",
      "Lead Generation",
      "Tailwind CSS",
      "Testimonials",
      "Responsive",
      "CTA",
      "Animations",
    ],
    code: quantumLeapHtml,
    imagePath: quantumLeapImg,
  },
  {
    id: "doctor-portfolio-3d",
    title: "Interactive 3D Medical Portfolio",
    category: "Healthcare",
    price: 12000,
    originalPrice: 16500,
    tags: [
      "3D Model Integration",
      "WebGL",
      "GSAP Animations",
      "Interactive UI",
      "Contact Us",
      "Single-Page App",
      "Patient Testimonials",
      "Three.js",
    ],
    code: doctorPortfolio3dHtml,
    imagePath: doctorPortfolio3dImg,
  },
  {
    id: "himalayan-builders-v1",
    title: "Himalayan Heritage Builders",
    category: "Construction",
    price: 18000,
    originalPrice: 18000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionSimpleHtml,
    imagePath: constructionSimpleImg,
  },
  {
    id: "himalayan-builders-v2",
    title: "Construction & Materials",
    category: "Construction",
    price: 25000,
    originalPrice: 30000,
    tags: [
      "3D Model Integration",
      "Three.js",
      "Interactive UI",
      "Tailwind CSS",
      "Corporate",
      "Dark Mode",
      "Responsive",
      "Testimonials",
      "FAQ",
      "Single-Page App"
    ],
    code: constructionHtml,
    imagePath: constructionImg,
  },
  {
    id: "saas-analytics-dashboard-v2",
    title: "Synergy BI - Analytics Dashboard",
    category: "SaaS / Business",
    price: 50000,
    originalPrice: 50000,
    tags: [
      "SaaS Platform",
      "Real-time Dashboard",
      "D3.js Data Viz",
      "Collaborative Tools",
      "Secure Authentication (RBAC)",
      "AI-Generated Insights",
      "PDF Reporting",
      "WebSockets",
    ],
    code: synergyBIHtml,
    imagePath: synergyBIImg,
  },
];
